flask_app/main/routes.py
import os
from flask import Blueprint, render_template, flash, redirect, url_for, request
from flask_login import current_user, login_required
from flask_app import photos, db
from flask_app.main.forms import ProfileForm, Update_ProfileForm
from flask_app.models import Profile, Region
from flask_app.models import User

main_bp = Blueprint('main', __name__)


@main_bp.route('/')
def index():
    file_list = []
    file_dir = "static/images/boroughpic/"
    for root, dirs, files in os.walk(file_dir):
        file_list = files
    file_list2 = []
    for f in file_list:
        file_list2.append(f.replace(".jpeg", ""))
    return render_template('index.html', title='Home page', file_list=file_list2)


@main_bp.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    profile = Profile.query.join(User, User.id == Profile.user_id).filter(User.id == current_user.id).first()
    if profile:
        return redirect(url_for('main.update_profile'))
    else:
        return redirect(url_for('main.create_profile'))


@main_bp.route('/create_profile', methods=['GET', 'POST'])
@login_required
def create_profile():
    form = ProfileForm()
    form.region_id.choices = [(r.id, r.region) for r in Region.query.order_by('region')]
    # print(len(form.region_id.choices))
    if request.method == 'POST' and form.validate_on_submit():
        filename = None  # Set the filename for the photo to None, this is the default if the user hasn't chosen to
        # add a profile photo
        if 'photo' in request.files:
            if request.files['photo'].filename != '':
                # Save the photo using the global variable photos to get the location to save to
                filename = photos.save(request.files['photo'])
        p = Profile(username=form.username.data, region_id=form.region_id.data, photo=filename,
                    description=form.description.data, user_id=current_user.id)
        db.session.add(p)
        db.session.commit()
        return redirect(url_for('main.display_profiles', username=p.username))
    return render_template('profile.html', form=form)


@main_bp.route('/update_profile', methods=['GET', 'POST'])
@login_required
def update_profile():
    profile = Profile.query.join(User, User.id == Profile.user_id).filter_by(
        id=current_user.id).first()  # Find the existing profile for this user
    form = Update_ProfileForm(
        obj=profile)
    form.region_id.choices = [(r.id, r.region) for r in Region.query.order_by('region')]
    if request.method == 'POST' and form.validate_on_submit():
        if 'photo' in request.files:
            filename = photos.save(request.files['photo'])
            profile.photo = filename  # Update the photo field
        # profile.area = form.area.data  # Update the country field
        # profile.bio = form.bio.data  # Update the bio field
        profile.username = form.username.data  # Update the user field
        profile.region_id = form.region_id.data  # Update the region id
        profile.description = form.description.data  # Updates the description field
        try:
            db.session.commit()  # Save the changes to the database
        except:
            # redirect to home page when the username does not match the login username
            return redirect('/')
        return redirect(url_for('main.display_profiles', username=profile.username))
    return render_template('update_profile.html', form=form, photo_filename=profile.photo)


@main_bp.route('/display_profiles', methods=['POST', 'GET'], defaults={'username': None})
@main_bp.route('/display_profiles/<username>/', methods=['POST', 'GET'])
@login_required
def display_profiles(username):
    results = None
    if username is None:
        if request.method == 'POST':
            term = request.form['search_term']
            if term == "":
                flash("Enter a name to search for")
                return redirect(url_for("main.index"))
            results = Profile.query.filter(Profile.username.contains(term)).all()
    else:
        results = Profile.query.filter_by(username=username).all()
    if not results:
        flash("Username not found.")
        return redirect(url_for("main.index"))
    filenames = []
    for result in results:
        if result.photo:
            filename = result.photo
            filenames.append(filename)
    return render_template('display_profile.html', profiles=zip(results, filenames))

flask_app/templates/_formhelpers.html
{% macro render_field(field) %}
  <dt>{{ field.label }}
  <dd>{{ field( **kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}

flask_app/templates/display_profile.html
{% extends 'layout.html' %}
{% set title = 'Profile Display' %}
{% from "_formhelpers.html" import render_field %}
{% block content %}
    {% for result, filename in profiles %}
        <div class="card" style="width: 25rem;">
            <img class="card-img-top" src="{{ url_for('static', filename='/img/'+filename) }}" alt="User profile photo">
            <div class="card-body">
                <h5 class="card-title">{{ result.username }}</h5>
                <h5 class="card-title">region id: {{ result.region_id }}</h5>
                <p class="card-text">{{ result.description }}</p>
            </div>
        </div>
    {% endfor %}
{% endblock %}

flask_app/templates/index.html
{% extends 'layout.html' %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/jquery.fancybox.css') }}">
<style>

    .ipic{
        float: left;
        width: 24%;
        text-align: center;
    }
        .fancybox img {
        margin-bottom: 5px;
        height: 150px;
        width: 99%;
    }
      .ipic span{
          color: black;
          font-size: 14px;

       }
</style>
{% endblock %}
{% block content %}
    <h1>{{ Introdution }}</h1>
    <h2 style="text-align:center;">This is the home page for business crime dash app.</h2>

    <p></p>
    <p>London Crime is a flask, web-based application created to display recent crime statistics in London, aiming to help
police officers conduct analysis and help citizens protect themselves. To provide a straightforward visual display of crime data,
the web app showcases total crime cases in London from 2020 to 2021 in a dashboard sorted by crime types and borough levels.
The data is provided by Metropolitan Police Service.</p>
    <p>Sign up an account to view the dashboard!</p>

        <div class="ibox-content">
            {% for f in file_list%}
                    <div class="ipic">
                        <a class="fancybox" href="../static/images/boroughpic/{{f}}.jpeg" title="{{f}}">
                            <img alt="image" src="../static/images/boroughpic/{{f}}.jpeg" />
                        </a>
                        <br/><span>{{f}}</span>
                    </div>
            {% endfor %}
        </div>


<script src="js/jquery.min.js?v=2.1.4"></script>
<script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/jquery.fancybox.js') }}"></script>
<script>
    $(document).ready(function () {
        $('.fancybox').fancybox({
            openEffect: 'none',
            closeEffect: 'none'
        });
    });
</script>

{% endblock %}

flask_app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap.css') }}">
    <script src="{{ url_for('static', filename='js/bootstrap.bundle.js') }}" defer></script>
    {% block css %}{% endblock %}
    <title>{{ title }}</title>

</head>
<body>
<header class="container-fluid">
    <br>
    {% include 'navbar.html' %}
</header>
<div id="flash-messages">
    {# Displays flashed messages on a page #}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
                <p class="alert alert-info" role="alert">{{ message }}</p>
            {% endfor %}
        {% endif %}
    {% endwith %}
</div>
<main>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
</main>
</body>
</html>

flask_app/templates/login.html
{% extends 'layout.html' %}
{% from "_formhelpers.html" import render_field %}
{% block content %}
    <form method=post action="{{ url_for('auth.login') }}">
        {{ form.csrf_token }}
        {{ render_field(form.email, class="form-control") }}
        {{ render_field(form.password, class="form-control") }}
        {{ render_field(form.remember, class="form-check-input") }}
    <div><button type="submit" id="btn-login" class="btn btn-primary">Login</button>
        <small class="text-muted ml-2">

        </small>
    </div>

    </form>
{% endblock %}

flask_app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">London Crime</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" id="nav-home" href="{{ url_for("main.index") }}">Home</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="/dashboard/">Dashboard</a>
                </li>
                {# Shows/hides login, signup and logout depending on status #}
                {% if current_user.is_anonymous %}
                    <li class="nav-item">
                        <a class="nav-link" id="nav-login" href="{{ url_for("auth.login") }}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="nav-signup" href="{{ url_for("auth.signup") }}">Sign up</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for("main.profile") }}">MyProfile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for("auth.logout") }}">Logout</a>
                    </li>
                {% endif %}
            </ul>
            <form class="d-flex" action="{{ url_for("main.display_profiles") }}" method="post">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                <input class="form-control me-2" type="search" placeholder="Search profile" aria-label="Search"
                       name="search_term">
                <button class="btn btn-outline-success" type="submit">Search profile</button>
            </form>
        </div>
    </div>
</nav>

flask_app/templates/profile.html
{% extends 'layout.html' %}
{% set title = 'Profile' %}
{% from "_formhelpers.html" import render_field %}
{% block content %}
    <form method="POST" action="{{ url_for('main.create_profile') }}" enctype="multipart/form-data">
        {{ form.csrf_token }}
        <dl>
            {{ render_field(form.username, class="form-control") }}
            {{ render_field(form.region_id, class="form-control") }}
            {{ render_field(form.description, id="input_file") }}
            {{ render_field(form.photo, class="custom-file", id="input_file") }}

        </dl>
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
    {% if photo_filename %}
        <p>Current photo filename: {{ photo_filename }}</p>
    {% endif %}
{% endblock %}

flask_app/templates/signup.html
{% extends 'layout.html' %}
{% from "_formhelpers.html" import render_field %}
{% block content %}

    {# Version using _formhelpers see: https://flask.palletsprojects.com/en/2.0.x/patterns/wtforms/#forms-in-templates #}
    <form method=post action="{{ url_for('auth.signup') }}">
        {{ form.csrf_token }}
        <dl>
            {{ render_field(form.first_name, class="form-control") }}
            {{ render_field(form.last_name, class="form-control") }}
            {{ render_field(form.email, class="form-control") }}
            {{ render_field(form.password, class="form-control") }}
            {{ render_field(form.password_repeat, class="form-control") }}
        </dl>
        <p><button type="submit" id="btn-signup" class="btn btn-primary">Sign up</button></p>
    </form>

    {# This version doesn't use the _formhelpers
    <form method="POST" action="{{ url_for('auth.signup') }}" class="row g3">
        {{ form.csrf_token }}
        <div class="col-md-6">
            {{ form.first_name.label(class='form-label') }} {{ form.first_name(class='form-control') }}
        </div>
        <div class="col-md-6">
            {{ form.last_name.label(class='form-label') }} {{ form.last_name(class='form-control') }}
        </div>
        <div class="col-md-12">
            {{ form.email.label(class='form-label') }} {{ form.email(class='form-control') }}
        </div>
        <div class="col-md-6">
            {{ form.password.label(class='form-label') }} {{ form.password(class='form-control') }}
        </div>
        <div class="col-md-6">
            {{ form.password_repeat.label(class='form-label') }} {{ form.password_repeat(class='form-control') }}
        </div>
        <div class="col-12">
            <br>
            <button type="submit" class="btn btn-primary">Sign up</button>
        </div>
    </form>
    #}

{% endblock %}

flask_app/templates/update_profile.html
{% extends 'layout.html' %}
{% set title = 'Profile' %}
{% from "_formhelpers.html" import render_field %}
{% block content %}
    <form method="POST" action="{{ url_for('main.update_profile') }}" enctype="multipart/form-data">
        {{ form.csrf_token }}
        <dl>
            {{ render_field(form.username, class="form-control") }}
            {{ render_field(form.region_id, class="form-control") }}
            {{ render_field(form.description, id="input_file") }}
            {{ render_field(form.photo, class="custom-file", id="input_file") }}
        </dl>
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
    {% if photo_filename %}
        <p>Current photo filename: {{ photo_filename }}</p>
    {% endif %}
{% endblock %}